-- phase_h_2_brand_dna_tenant_unique_constraint
--
-- APPLIED LIVE via Supabase MCP on 2026-08-23 during the pre-launch demo
-- dry-run (DB_AUDIT_REPORT.md Section 41). This file is the post-hoc
-- tracked record of that change, reconstructed from
-- supabase_migrations.schema_migrations so the repo matches live schema.
--
-- Second half of the brand_dna fix from phase_h_1 (dry-run, 2026-08-23).
-- After fixing the missing `tagline` column, the same upsert still failed
-- with "there is no unique or exclusion constraint matching the ON CONFLICT
-- specification" -- brand_dna has only ever had a PK on `id`, never a
-- unique constraint on tenant_id, despite every read/write path in the app
-- (both onboarding wizards, controllers/tenants.js's completeness check,
-- controllers/calls.js/invoices.js's reads, server.js's draft-generation
-- lookup) treating it as exactly one row per tenant via
-- `.eq('tenant_id', ...).single()` / `onConflict: 'tenant_id'`.
-- Confirmed zero duplicate tenant_id rows exist (1 row total in the live
-- table) before adding this, so the constraint is safe to add with no data
-- cleanup needed. This is what both onboarding brand_dna upserts have
-- needed since day one to ever succeed.
alter table public.brand_dna
  add constraint brand_dna_tenant_id_key unique (tenant_id);
