// AUTO-GENERATED by Supabase MCP — 2026-06-26
// Do not edit manually. Regenerate via: supabase gen types typescript

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      brand_dna: {
        Row: {
          brand_name: string
          brand_voice_guidelines: string
          created_at: string | null
          id: number
          product_catalog: Json
          tenant_id: string | null
        }
        Insert: {
          brand_name: string
          brand_voice_guidelines: string
          created_at?: string | null
          id?: number
          product_catalog: Json
          tenant_id?: string | null
        }
        Update: {
          brand_name?: string
          brand_voice_guidelines?: string
          created_at?: string | null
          id?: number
          product_catalog?: Json
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "brand_dna_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      closed_deals: {
        Row: {
          associated_phone: string | null
          closed_at: string | null
          final_amount: number
          id: number
          invoice_number: string | null
          lead_id: number | null
        }
        Insert: {
          associated_phone?: string | null
          closed_at?: string | null
          final_amount: number
          id?: number
          invoice_number?: string | null
          lead_id?: number | null
        }
        Update: {
          associated_phone?: string | null
          closed_at?: string | null
          final_amount?: number
          id?: number
          invoice_number?: string | null
          lead_id?: number | null
        }
        Relationships: []
      }
      company_knowledge: {
        Row: {
          brand_id: number | null
          content_chunk: string
          created_at: string | null
          document_title: string
          embedding: string | null
          id: number
        }
        Insert: {
          brand_id?: number | null
          content_chunk: string
          created_at?: string | null
          document_title: string
          embedding?: string | null
          id?: number
        }
        Update: {
          brand_id?: number | null
          content_chunk?: string
          created_at?: string | null
          document_title?: string
          embedding?: string | null
          id?: number
        }
        Relationships: [
          {
            foreignKeyName: "company_knowledge_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brand_dna"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory: {
        Row: {
          created_at: string
          description: string | null
          id: string
          price: number
          product_name: string
          sku: string | null
          status: string | null
          stock_count: number
          tenant_id: string | null
          unit: string | null
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          price: number
          product_name: string
          sku?: string | null
          status?: string | null
          stock_count?: number
          tenant_id?: string | null
          unit?: string | null
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          price?: number
          product_name?: string
          sku?: string | null
          status?: string | null
          stock_count?: number
          tenant_id?: string | null
          unit?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "inventory_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      quotes: {
        Row: {
          accepted_at: string | null
          created_at: string
          currency: string
          id: string
          lead_id: string | null
          line_items: Json
          notes: string | null
          quote_number: string
          sent_at: string | null
          status: string
          subtotal: number
          tax_amount: number | null
          tax_rate: number
          tenant_id: string
          total: number | null
          updated_at: string
          valid_until: string | null
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          currency?: string
          id?: string
          lead_id?: string | null
          line_items?: Json
          notes?: string | null
          quote_number: string
          sent_at?: string | null
          status?: string
          subtotal?: number
          tax_amount?: number | null
          tax_rate?: number
          tenant_id: string
          total?: number | null
          updated_at?: string
          valid_until?: string | null
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          currency?: string
          id?: string
          lead_id?: string | null
          line_items?: Json
          notes?: string | null
          quote_number?: string
          sent_at?: string | null
          status?: string
          subtotal?: number
          tax_amount?: number | null
          tax_rate?: number
          tenant_id?: string
          total?: number | null
          updated_at?: string
          valid_until?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quotes_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "smart_leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      smart_interactions: {
        Row: {
          channel: string
          created_at: string | null
          direction: string | null
          id: string
          lead_id: string | null
          message_content: string | null
          raw_payload: Json | null
          tenant_id: string | null
        }
        Insert: {
          channel?: string
          created_at?: string | null
          direction?: string | null
          id?: string
          lead_id?: string | null
          message_content?: string | null
          raw_payload?: Json | null
          tenant_id?: string | null
        }
        Update: {
          channel?: string
          created_at?: string | null
          direction?: string | null
          id?: string
          lead_id?: string | null
          message_content?: string | null
          raw_payload?: Json | null
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "smart_interactions_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "smart_leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "smart_interactions_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      smart_leads: {
        Row: {
          communication_preference: string | null
          company_name: string | null
          created_at: string | null
          customer_name: string | null
          email: string | null
          id: string
          intent_category: string | null
          language: string
          last_contacted_at: string | null
          lead_channel_id: string | null
          lead_source: string | null
          phone_number: string | null
          product_interest: string | null
          ptc_score: number | null
          source_channel: string | null
          status: string | null
          tenant_id: string | null
          triage_status: string | null
          updated_at: string
        }
        Insert: {
          communication_preference?: string | null
          company_name?: string | null
          created_at?: string | null
          customer_name?: string | null
          email?: string | null
          id?: string
          intent_category?: string | null
          language?: string
          last_contacted_at?: string | null
          lead_channel_id?: string | null
          lead_source?: string | null
          phone_number?: string | null
          product_interest?: string | null
          ptc_score?: number | null
          source_channel?: string | null
          status?: string | null
          tenant_id?: string | null
          triage_status?: string | null
          updated_at?: string
        }
        Update: {
          communication_preference?: string | null
          company_name?: string | null
          created_at?: string | null
          customer_name?: string | null
          email?: string | null
          id?: string
          intent_category?: string | null
          language?: string
          last_contacted_at?: string | null
          lead_channel_id?: string | null
          lead_source?: string | null
          phone_number?: string | null
          product_interest?: string | null
          ptc_score?: number | null
          source_channel?: string | null
          status?: string | null
          tenant_id?: string | null
          triage_status?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "smart_leads_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          created_at: string
          email_domain: string | null
          id: string
          name: string
          plan: string
          updated_at: string
          whatsapp_phone_id: string | null
        }
        Insert: {
          created_at?: string
          email_domain?: string | null
          id?: string
          name: string
          plan?: string
          updated_at?: string
          whatsapp_phone_id?: string | null
        }
        Update: {
          created_at?: string
          email_domain?: string | null
          id?: string
          name?: string
          plan?: string
          updated_at?: string
          whatsapp_phone_id?: string | null
        }
        Relationships: []
      }
      whatsapp_sessions: {
        Row: {
          id: number
          phone_number: string | null
          session_data: string | null
          status: string | null
          tenant_id: string
          updated_at: string | null
        }
        Insert: {
          id?: number
          phone_number?: string | null
          session_data?: string | null
          status?: string | null
          tenant_id: string
          updated_at?: string | null
        }
        Update: {
          id?: number
          phone_number?: string | null
          session_data?: string | null
          status?: string | null
          tenant_id?: string
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      match_company_knowledge: {
        Args: {
          match_count: number
          match_threshold: number
          p_brand_id: number
          query_embedding: string
        }
        Returns: {
          content_chunk: string
          id: number
          similarity: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
